### ISSUE TITLE
Program does not download audio of a video when selected .mp3

### ISSUE THREAD

**Issue by SoundCrafterYT** [yt-dlg/yt-dlg#12]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '--all-subs', '-k', '-o', "D:\\The Sound Crafter Company's Official Folder\\Videos\\Download\\Videos\\%(uploader)s-%(title)s.%(ext)s", '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--ignore-config', '--hls-prefer-native', 'https://youtu.be/d3NxSVj2X8g']
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] exe versions: none
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Proxy map: {}
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Loaded 1782 extractors
2023-02-21 09:58:48,048-DEBUG-Worker_1-[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
2023-02-21 09:58:48,049-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
2023-02-21 09:58:48,049-DEBUG-Worker_1-[debug] Default format spec: best/bestvideo+bestaudio
2023-02-21 09:58:48,049-DEBUG-Worker_1-[debug] Invoking http downloader on "https://rr4---sn-qpbpu8-c0qs.googlevideo.com/videoplayback?expire=1676991526&ei=xof0Y670CYjh1wKM5rvIDA&ip=2a01%3A36d%3A115%3Ab78%3A99df%3A9d80%3Ad2b6%3Aa329&id=o-ANFY2cF_z6QCtg754K7skwPCx9WQi1Qv5JN5AYJrarXj&itag=22&source=youtube&requiressl=yes&mh=KH&mm=31%2C29&mn=sn-qpbpu8-c0qs%2Csn-c0q7lnly&ms=au%2Crdu&mv=m&mvi=4&pl=54&initcwndbps=1113750&spc=H3gIhn8UtmRKHGfx4fpmz26yPV5VO24&vprv=1&svpuc=1&mime=video%2Fmp4&ratebypass=yes&dur=337.966&lmt=1550470612064944&mt=1676969599&fvip=2&fexp=24007246&c=ANDROID&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIcqLTGuTVw3KwEyOeAQUYgzmpuoXdasb8aHjuM-jjrLAiBpCaMZU-F12j23BWeeUcBIrYhQFOK3HutjqisC7QHXxA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgVFPdwiTry4ZNuTKHqAOg_5Y6BMrSNac3PwU1HqiTYUACIQD9JgccG5_S0bDOe3m63h91v9OSMiVsQXqr-5rlDuCBCA%3D%3D"
2023-02-21 09:58:48,049-DEBUG-Worker_1-[debug] File locking is not supported. Proceeding without locking
2023-02-21 09:58:48,049-DEBUG-Worker_1-ERROR: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
2023-02-21 09:58:48,049-DEBUG-Worker_1-Traceback (most recent call last):
2023-02-21 09:58:48,049-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 3446, in run_pp
2023-02-21 09:58:48,049-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 24, in run
2023-02-21 09:58:48,049-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
2023-02-21 09:58:48,049-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 488, in run
2023-02-21 09:58:48,050-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 241, in get_audio_codec
2023-02-21 09:58:48,050-DEBUG-Worker_1-yt_dlp.utils.PostProcessingError: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
2023-02-21 09:58:48,050-DEBUG-Worker_1-Child process exited with non-zero code: 1

```

#### What is the expected behavior?

Download the audio file

#### What happens instead?

Downloads the video itself and status shows Error

---
#### What operating system do you use ?

Microsoft Windows [Version 10.0.19044.2604]

---

**Comment by oleksis** [comment]
To process/extract audio (mp3) from Video you need install FFmpeg: https://yt-dlg.github.io/yt-dlg/Install-FFmpeg-on-Windows.html

**Comment by oleksis** [comment]
Add another options `--ffmpeg-location` to the docs: [Configure FFmpeg on yt-dlg](https://yt-dlg.github.io/yt-dlg/Install-FFmpeg-on-Windows.html#configure-ffmpeg-on-yt-dlg)
