### ISSUE TITLE
Yt-dlg only downloads youtube videos as .webm files, or before reinstalling yt-dlg, as .m4a files, even when choosing the .mp3 file type option

### ISSUE THREAD

**Issue by sfilie03** [yt-dlg/yt-dlg#28]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '-o', 'C:\\Users\\User\\Downloads\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y']
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (win_exe)
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] exe versions: none
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Proxy map: {}
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Request Handlers: urllib, requests, websockets, curl_cffi
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Loaded 1838 extractors
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] [youtube] Extracting signature function js_0ccfa671_105
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Loading youtube-sigfuncs.js_0ccfa671_105 from cache
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Loading youtube-nsig.0ccfa671 from cache
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig GTO-geSm1hOzEnC => eEhmXkOtdDvleQ
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Loading youtube-nsig.0ccfa671 from cache
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig tKa9PgVlhXzbNzm => d95wDJY6E6exdw
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Invoking http downloader on "https://rr4---sn-gvbxgn-tvf6.googlevideo.com/videoplayback?expire=1731804190&ei=vuc4Z8fuKcGkir4PxO6JmAw&ip=2607%3Afea8%3Ae366%3A1000%3Ae850%3Abc8e%3A8a90%3A2fb3&id=o-ALMJTlxyDvfhZJeBn5-aW6P-fDxbvIvnlzwAv_-i-fxX&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1731782590%2C&mh=yF&mm=31%2C29&mn=sn-gvbxgn-tvf6%2Csn-gvbxgn-tt1ee&ms=au%2Crdu&mv=m&mvi=4&pl=41&rms=au%2Cau&gcr=ca&initcwndbps=1748750&spc=qtApAahtpOqU8raQ85Ob7-njmorWRFCi_PWE2qiGd09ikUc&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=4934666&dur=295.861&lmt=1700456040073261&mt=1731782244&fvip=4&keepalive=yes&fexp=51299154%2C51312688%2C51326932&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANWNH5eu6D-wx9zooHU2VPt06WQVfZ48eOLjKFt8NUaaAiBvXsXtowj3ohu6feSYIkrfLzxoo34DAJDCzDk1zXT3Bw%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAO869JY1Td5Q9peNbrX_d1pbRLcBDJ8Eh6w0LUOf-5k2AiA0zBH55u0GpHprTcqXWcCYQjF8vJQqMmDN6EjpkgvdLQ%3D%3D"
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] File locking is not supported. Proceeding without locking
2024-11-16 13:43:13,450-DEBUG-Worker_1-ERROR: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-16 13:43:13,450-DEBUG-Worker_1-Traceback (most recent call last):
2024-11-16 13:43:13,450-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 3701, in run_pp
2024-11-16 13:43:13,450-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 23, in run
2024-11-16 13:43:13,454-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
2024-11-16 13:43:13,454-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 494, in run
2024-11-16 13:43:13,454-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 242, in get_audio_codec
2024-11-16 13:43:13,454-DEBUG-Worker_1-yt_dlp.utils.PostProcessingError: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-16 13:43:13,454-DEBUG-Worker_1-Child process exited with non-zero code: 1
```

#### What operating system do you use ?
Microsoft Windows 10 Pro 22H2 19045.5131

#### List of actions to perform to reproduce the problem:

  1. Open yt-dlg.exe.
  2. Add a URL to download an .mp3 file from a youtube video.
  3. Close yt-dlg.exe.

#### What is the expected behaviour ?
Yt-dlg should download a youtube URL as an .mp3 file if that's the selected download file type, and save it to the computer.

#### What happens instead ?
Yt-dlg downloads and saves a youtube URL as a .webm file, or as .m4a files if I put "--audio-format mp3 --audio-quality 128 -f 'bestaudio[asr=44100]'" in the options, extra settings, even though I selected .mp3 files as the download file type.

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/oleksis/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Microsoft Windows 10 Pro 22H2 19045.5131

---

Yt-dlg one one of my computers works properly, and downloads files in the correct selected file type, however on another computer, it doesn't download youtube URLs as .mp3 files when that's the selected file type. It only saves them as .webm files, or as .m4a files if I put "--audio-format mp3 --audio-quality 128 -f 'bestaudio[asr=44100]'" in the options, extra settings, even after using the update option. Also, the file status says "error" after downloading the file. I'm using yt-dlg 1.8.5, installed in the default installation directory, and have already selected the update option, and chosen the download file type as .mp3 files. I've already tried reinstalling yt-dlg, but it has the same issue. How do I get it to download .mp3 files, especially with custom audio settings? Is there a way to fix that?

**Comment by chamaramokai** [comment]
Have you changed the interface from default to mp3? 
![image](https://github.com/user-attachments/assets/5345fa09-c4fa-4319-8258-76a9057006cc)

**Comment by chamaramokai** [comment]
It says you are missing ffmpeg on the log. You may need to install it on windows to convert it from the webm to mp3.  Be sure to add it to your PATH on system environment and restart the application after installing/adding to path.

**Comment by sfilie03** [comment]
@chamaramokai thanks. That's helpful information.

**Comment by dakshcs** [comment]
@chamaramokai @IoanPaleru +1 on this issue. i too am facing this problem.

log after i cancel it for showing .webm for extension:

```
2025-01-08 23:54:16,683-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '-o', 'C:\\Users\\ravi9\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--ignore-config', '--hls-prefer-native', '--embed-thumbnail', '--add-metadata', 'https://youtube.com/playlist?list=PL_ba-gJbYptmDaH0nXG4ftEll8eKXwkNd']
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] exe versions: ffmpeg 2025-01-05-git-19c95ecbff-full_build-www.gyan.dev (setts), ffprobe 2025-01-05-git-19c95ecbff-full_build-www.gyan.dev
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] Proxy map: {}
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] Request Handlers: urllib, requests, websockets, curl_cffi
2025-01-08 23:54:16,684-DEBUG-Worker_1-[debug] Loaded 1837 extractors
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] Skipping writing playlist thumbnail
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] [youtube] 9FfGO915EZ8: ios client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] [youtube] Extracting signature function js_a5032d18_110
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] Loading youtube-sigfuncs.js_a5032d18_110 from cache
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] Loading youtube-nsig.a5032d18 from cache
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig PiPAfffOhKN8AZNn => 9tR7uMYLRKhtVg
2025-01-08 23:54:16,685-DEBUG-Worker_1-[debug] Loading youtube-nsig.a5032d18 from cache
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig KwENunZWb8NpiDyw => j9sPtj1Mn04Q3g
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] [youtube] Extracting signature function js_a5032d18_106
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] Loading youtube-sigfuncs.js_a5032d18_106 from cache
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] Invoking http downloader on "https://rr6---sn-ci5gup-qxaes.googlevideo.com/videoplayback?expire=1736382247&ei=x8J-Z57BMuS09fwPwbe38QY&ip=122.161.48.21&id=o-AKAsL8sZm7Xvlsqu62OnqSJONhzYdBoAbAuc1Av5Ne8C&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1736360647%2C&mh=rN&mm=31%2C26&mn=sn-ci5gup-qxaes%2Csn-cvh7knsz&ms=au%2Conr&mv=m&mvi=6&pl=23&rms=au%2Cau&gcr=in&initcwndbps=1958750&bui=AfMhrI8QWOXx4bQdIE4jY2jb4T5rR-L2a27tcgQtRQAj1auE1ye1LgZAKtIzQZJ4YD3XoGsS9Xr3dzWO&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=gbnGaYl2y_rLwOPlHvX8RZIQ&rqh=1&gir=yes&clen=4171377&dur=234.861&lmt=1714521436334808&mt=1736359998&fvip=3&keepalive=yes&fexp=51326932%2C51331020%2C51335594%2C51371294&c=MWEB&sefc=1&txp=2318224&n=j9sPtj1Mn04Q3g&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhALhAZCN5fPktuLEcqTbGb7xqpQppZy7rHFTOtkaHFZcZAiBBq_KPaKEnYu9U40OJeaBVFgfzgw2Jzmc22nQhOcFtGg%3D%3D&sig=AJfQdSswRQIhAKplgVDqqJ2bsUWJCR16xz56fsa7Vk_gUUWnzFCkC2MoAiAr2rg5NgdleY802aDmXhLyQNVxb6hi-gETxlcpNDPydg%3D%3D"
2025-01-08 23:54:16,686-DEBUG-Worker_1-[debug] File locking is not supported. Proceeding without locking
2025-01-08 23:54:16,687-DEBUG-Worker_1-[debug] ffmpeg command line: ffprobe -show_streams file:C:\Users\ravi9\ANDRETTI.webm
2025-01-08 23:54:16,687-DEBUG-Worker_1-[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:C:\Users\ravi9\ANDRETTI.webm -vn -acodec libmp3lame -q:a 0.0 -movflags +faststart file:C:\Users\ravi9\ANDRETTI.mp3
2025-01-08 23:54:16,687-DEBUG-Worker_1-[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:C:\Users\ravi9\ANDRETTI.mp3 -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=ANDRETTI" -metadata "date=20230701" -metadata "description=Provided to YouTube by Exceleration Music
2025-01-08 23:54:16,687-DEBUG-Worker_1-ANDRETTI · 454
2025-01-08 23:54:16,687-DEBUG-Worker_1-4 REAL
2025-01-08 23:54:16,687-DEBUG-Worker_1- 2021 MATH / Honeymoon
2025-01-08 23:54:16,687-DEBUG-Worker_1-Released on: 2021-03-16
2025-01-08 23:54:16,687-DEBUG-Worker_1-Main  Artist: 454
2025-01-08 23:54:16,687-DEBUG-Worker_1-Composer: 454
2025-01-08 23:54:16,688-DEBUG-Worker_1-Lyricist: 454
2025-01-08 23:54:16,688-DEBUG-Worker_1-Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Exceleration Music
2025-01-08 23:54:16,688-DEBUG-Worker_1-ANDRETTI · 454
2025-01-08 23:54:16,688-DEBUG-Worker_1-4 REAL
2025-01-08 23:54:16,688-DEBUG-Worker_1- 2021 MATH / Honeymoon
2025-01-08 23:54:16,688-DEBUG-Worker_1-Released on: 2021-03-16
2025-01-08 23:54:16,688-DEBUG-Worker_1-Main  Artist: 454
2025-01-08 23:54:16,688-DEBUG-Worker_1-Composer: 454
2025-01-08 23:54:16,689-DEBUG-Worker_1-Lyricist: 454
2025-01-08 23:54:16,689-DEBUG-Worker_1-Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=9FfGO915EZ8" -metadata "comment=https://www.youtube.com/watch?v=9FfGO915EZ8" -metadata "artist=454" -metadata "album=4 REAL" -movflags +faststart file:C:\Users\ravi9\ANDRETTI.temp.mp3
2025-01-08 23:54:16,689-DEBUG-Worker_1-[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:C:\Users\ravi9\ANDRETTI.webp -update 1 -movflags +faststart file:C:\Users\ravi9\ANDRETTI.png
2025-01-08 23:54:16,689-DEBUG-Worker_1-[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:C:\Users\ravi9\ANDRETTI.mp3 -i file:C:\Users\ravi9\ANDRETTI.png -c copy -map 0:0 -map 1:0 -write_id3v1 1 -id3v2_version 3 -metadata:s:v "title=\"Album cover\"" -metadata:s:v "comment=Cover (front)" -movflags +faststart file:C:\Users\ravi9\ANDRETTI.temp.mp3
2025-01-08 23:54:16,689-DEBUG-Worker_1-[debug] [youtube] iEjjX-gI4N8: ios client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
2025-01-08 23:54:16,689-DEBUG-Worker_1-[debug] Loading youtube-nsig.a5032d18 from cache
2025-01-08 23:54:16,689-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig Lg8k7EvOglSTFug_ => YYKfficfSKenVQ
2025-01-08 23:54:16,689-DEBUG-Worker_1-[debug] Loading youtube-nsig.a5032d18 from cache
2025-01-08 23:54:16,690-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig AJdK6vXbvnZ_BOSe => Qor2OET3cV7tKQ
2025-01-08 23:54:16,690-DEBUG-Worker_1-[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
2025-01-08 23:54:16,690-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
2025-01-08 23:54:16,690-DEBUG-Worker_1-ERROR: [Errno 22] Invalid argument
2025-01-08 23:54:16,690-DEBUG-Worker_1-Traceback (most recent call last):
2025-01-08 23:54:16,690-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
2025-01-08 23:54:16,690-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1790, in __extract_info
2025-01-08 23:54:16,690-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1849, in process_ie_result
2025-01-08 23:54:16,690-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 2997, in process_video_result
2025-01-08 23:54:16,691-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 2995, in to_screen
2025-01-08 23:54:16,691-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 943, in to_screen
2025-01-08 23:54:16,691-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 924, in _write_string
2025-01-08 23:54:16,691-DEBUG-Worker_1-  File "yt_dlp\utils\_utils.py", line 1481, in write_string
2025-01-08 23:54:16,691-DEBUG-Worker_1-OSError: [Errno 22] Invalid argument
2025-01-08 23:54:16,691-DEBUG-Worker_1-ERROR: [Errno 22] Invalid argument
2025-01-08 23:54:16,691-DEBUG-Worker_1-Traceback (most recent call last):
2025-01-08 23:54:16,691-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
2025-01-08 23:54:16,691-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1790, in __extract_info
2025-01-08 23:54:16,693-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1919, in process_ie_result
2025-01-08 23:54:16,693-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 2063, in __process_playlist
2025-01-08 23:54:16,693-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 943, in to_screen
2025-01-08 23:54:16,693-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 924, in _write_string
2025-01-08 23:54:16,693-DEBUG-Worker_1-  File "yt_dlp\utils\_utils.py", line 1481, in write_string
2025-01-08 23:54:16,693-DEBUG-Worker_1-OSError: [Errno 22] Invalid argument
2025-01-08 23:54:16,693-DEBUG-Worker_1-Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
2025-01-08 23:54:16,693-DEBUG-Worker_1-OSError: [Errno 22] Invalid argument
```






![image](https://github.com/user-attachments/assets/82cb8945-5df7-4dc7-a4aa-3c0ac502d05c)

**Comment by dakshcs** [comment]
@oleksis

**Comment by oleksis** [comment]
For convert to mp3 you need install FFmpeg: https://yt-dlg.github.io/yt-dlg/Install-FFmpeg-on-Windows.html

**Comment by tranric** [comment]
@phoenix277yt My issue in #29 is not the same.  My ffmpeg is installed and is on Ubuntu not on windows as well as my config/command also specifies the location using "--ffmpeg-location" verified with the bin location under "/usr/bin/ffmpeg" with it not being detected for some reason no matter install method for both DLG and/or FFMPEG. No need to ping me specifically for this issue as it is unrelated to #29 .  Your log also says FFmpeg location is not installed/detected.

**Comment by dakshcs** [comment]
> No need to ping me specifically for this issue as it is unrelated to #29 .

never did but okay
