### ISSUE TITLE
ubuntu ffmpeg not being detected - fresh install

### ISSUE THREAD

**Issue by chamaramokai** [yt-dlg/yt-dlg#29]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.8.5**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [x] Question
- [x] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl** - Not there on Ubuntu install; enabled "Debug CLI Backend" instead.
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '--all-subs', '-o', '/home/leiroux/Videos/%(title)s-%(id)s-%(resolution)s-%(upload_date)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--embed-thumbnail', '--add-metadata', '--ffmpeg-location', '/usr/bin/ffmpeg', '--sub-langs', 'all', '--compat-options', 'no-live-chat', '--embed-subs', '--recode-video', 'mp4', '--format', 'bestvideo+bestaudio+mergeall', '--embed-thumbnail', '--merge-output-format', 'mkv', '--embed-metadata', '--embed-chapters', '--yes-playlist', 'https://www.youtube.com/watch?v=-f5xLVvvbFU']
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (zip)
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Compatibility options: no-live-chat
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
2024-11-19 11:46:52,809-DEBUG-Worker_1-WARNING: ffmpeg-location /usr/bin/ffmpeg does not exist! Continuing without ffmpeg
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] exe versions: none
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.25.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Proxy map: {}
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Request Handlers: urllib
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Loaded 1837 extractors
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Loading youtube-nsig.2d24ba15 from cache
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig flMKvEuieY3KVAidH => OYrpplSYCVpOVQ
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Loading youtube-nsig.2d24ba15 from cache
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig fijXXZkSNSnIeXAOq => kvx9MGIgw62hrQ
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=-f5xLVvvbFU&ei=8cA8Z9OXG5uBkucPqqqZgQU&caps=asr&opi=112496729&exp=xbt&xoaf=4&hl=en&ip=0.0.0.0&ipbits=0&expire=1732060001&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cexp%2Cxoaf&signature=2497F692F127556E6912712D24A35C9CE885B495.0FC21095F70723D1FAA03FC1475199181957A10D&key=yt8&lang=en&fmt=vtt"
2024-11-19 11:46:52,809-DEBUG-Worker_1-WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Invoking http downloader on "https://rr3---sn-gvbxgn-tt1ee.googlevideo.com/videoplayback?expire=1732056401&ei=8cA8Z5PFDYa0kucPkseM4Qk&ip=99.246.9.103&id=o-ABsJpCXoNeJ_K5ZO75nDaTGf3ukPenb8G8N_Y7gMMQzZ&itag=399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1732034801%2C&mh=vi&mm=31%2C26&mn=sn-gvbxgn-tt1ee%2Csn-vgqsknzl&ms=au%2Conr&mv=m&mvi=3&pl=23&rms=au%2Cau&initcwndbps=1751250&spc=qtApAcbjXO0tl8h1cLcXEe1sOauvO-845mDZ4mYRhNWG5SI&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=299747196&dur=1984.315&lmt=1726429885881455&mt=1732034006&fvip=3&keepalive=yes&fexp=51299154%2C51312688%2C51326932%2C51335593%2C51347747&c=IOS&txp=5537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAK1vFgPYIQm1_wmMcGi-12wI9P_h690yyuUIePIQc7HCAiEAxHCjXB5sgZCiR2OXwYdMyldev_3xxdnzmKjP2nE_hZU%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRAIgIs1HQ-toA1QoK93jQ9Fz57jvPi3YZh_z_NAz8V_KLZQCIHs0vEXFyRP1F_GsI-fuz5F-OfK_bczk-6GZepRBX_d9"
2024-11-19 11:46:52,809-DEBUG-Worker_1-[debug] Invoking http downloader on "https://rr3---sn-gvbxgn-tt1ee.googlevideo.com/videoplayback?expire=1732056401&ei=8cA8Z5PFDYa0kucPkseM4Qk&ip=99.246.9.103&id=o-ABsJpCXoNeJ_K5ZO75nDaTGf3ukPenb8G8N_Y7gMMQzZ&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1732034801%2C&mh=vi&mm=31%2C26&mn=sn-gvbxgn-tt1ee%2Csn-vgqsknzl&ms=au%2Conr&mv=m&mvi=3&pl=23&rms=au%2Cau&initcwndbps=1751250&spc=qtApAcbjXO0tl8h1cLcXEe1sOauvO-845mDZ4mYRhNWG5SI&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=32112533&dur=1984.341&lmt=1726400851205184&mt=1732034006&fvip=3&keepalive=yes&fexp=51299154%2C51312688%2C51326932%2C51335593%2C51347747&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgVb2Fdg6n7eoNDUzJ9wSuho26joHrOMbn-pt4WlJ7nNICIEKOTu3lSwUyfSeNfn6TnCsVIs0DglkQi-PiQNCCCRA2&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRAIgIs1HQ-toA1QoK93jQ9Fz57jvPi3YZh_z_NAz8V_KLZQCIHs0vEXFyRP1F_GsI-fuz5F-OfK_bczk-6GZepRBX_d9"
2024-11-19 11:46:52,809-DEBUG-Worker_1-ERROR: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-19 11:46:52,809-DEBUG-Worker_1-Traceback (most recent call last):
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3700, in run_pp
2024-11-19 11:46:52,809-DEBUG-Worker_1-    files_to_delete, infodict = pp.run(infodict)
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
2024-11-19 11:46:52,809-DEBUG-Worker_1-    ret = func(self, info, *args, **kwargs)
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 127, in wrapper
2024-11-19 11:46:52,809-DEBUG-Worker_1-    return func(self, info)
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 573, in run
2024-11-19 11:46:52,809-DEBUG-Worker_1-    self.run_ffmpeg(filename, outpath, self._options(target_ext))
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 374, in run_ffmpeg
2024-11-19 11:46:52,809-DEBUG-Worker_1-    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
2024-11-19 11:46:52,809-DEBUG-Worker_1-    return self.real_run_ffmpeg(
2024-11-19 11:46:52,809-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 334, in real_run_ffmpeg
2024-11-19 11:46:52,809-DEBUG-Worker_1-    self.check_version()
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 232, in check_version
2024-11-19 11:46:52,810-DEBUG-Worker_1-    raise FFmpegPostProcessorError('ffmpeg not found. Please install or provide the path using --ffmpeg-location')
2024-11-19 11:46:52,810-DEBUG-Worker_1-yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-19 11:46:52,810-DEBUG-Worker_1-ERROR: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-19 11:46:52,810-DEBUG-Worker_1-Traceback (most recent call last):
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3700, in run_pp
2024-11-19 11:46:52,810-DEBUG-Worker_1-    files_to_delete, infodict = pp.run(infodict)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
2024-11-19 11:46:52,810-DEBUG-Worker_1-    ret = func(self, info, *args, **kwargs)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 127, in wrapper
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return func(self, info)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 662, in run
2024-11-19 11:46:52,810-DEBUG-Worker_1-    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return self.real_run_ffmpeg(
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 334, in real_run_ffmpeg
2024-11-19 11:46:52,810-DEBUG-Worker_1-    self.check_version()
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 232, in check_version
2024-11-19 11:46:52,810-DEBUG-Worker_1-    raise FFmpegPostProcessorError('ffmpeg not found. Please install or provide the path using --ffmpeg-location')
2024-11-19 11:46:52,810-DEBUG-Worker_1-yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-19 11:46:52,810-DEBUG-Worker_1-ERROR: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-19 11:46:52,810-DEBUG-Worker_1-Traceback (most recent call last):
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3700, in run_pp
2024-11-19 11:46:52,810-DEBUG-Worker_1-    files_to_delete, infodict = pp.run(infodict)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
2024-11-19 11:46:52,810-DEBUG-Worker_1-    ret = func(self, info, *args, **kwargs)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 127, in wrapper
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return func(self, info)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 711, in run
2024-11-19 11:46:52,810-DEBUG-Worker_1-    self.run_ffmpeg_multiple_files(
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return self.real_run_ffmpeg(
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 334, in real_run_ffmpeg
2024-11-19 11:46:52,810-DEBUG-Worker_1-    self.check_version()
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 232, in check_version
2024-11-19 11:46:52,810-DEBUG-Worker_1-    raise FFmpegPostProcessorError('ffmpeg not found. Please install or provide the path using --ffmpeg-location')
2024-11-19 11:46:52,810-DEBUG-Worker_1-yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-19 11:46:52,810-DEBUG-Worker_1-ERROR: [Errno 2] No such file or directory: '/home/leiroux/Videos/The Ultimate Roulette of Speedrunning--f5xLVvvbFU-1920x1080-20221007.mkv'
2024-11-19 11:46:52,810-DEBUG-Worker_1-Traceback (most recent call last):
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 1624, in wrapper
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return func(self, *args, **kwargs)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 1780, in __extract_info
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return self.process_ie_result(ie_result, download, extra_info)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 1839, in process_ie_result
2024-11-19 11:46:52,810-DEBUG-Worker_1-    ie_result = self.process_video_result(ie_result, download=download)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3010, in process_video_result
2024-11-19 11:46:52,810-DEBUG-Worker_1-    self.process_info(new_info)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 177, in wrapper
2024-11-19 11:46:52,810-DEBUG-Worker_1-    return func(self, *args, **kwargs)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3556, in process_info
2024-11-19 11:46:52,810-DEBUG-Worker_1-    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3740, in post_process
2024-11-19 11:46:52,810-DEBUG-Worker_1-    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3722, in run_all_pps
2024-11-19 11:46:52,810-DEBUG-Worker_1-    info = self.run_pp(pp, info)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/YoutubeDL.py", line 3700, in run_pp
2024-11-19 11:46:52,810-DEBUG-Worker_1-    files_to_delete, infodict = pp.run(infodict)
2024-11-19 11:46:52,810-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
2024-11-19 11:46:52,810-DEBUG-Worker_1-    ret = func(self, info, *args, **kwargs)
2024-11-19 11:46:52,811-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/common.py", line 127, in wrapper
2024-11-19 11:46:52,811-DEBUG-Worker_1-    return func(self, info)
2024-11-19 11:46:52,811-DEBUG-Worker_1-  File "/home/leiroux/snap/yt-dlg/22/.config/yt-dlg/yt-dlp/yt_dlp/postprocessor/embedthumbnail.py", line 87, in run
2024-11-19 11:46:52,811-DEBUG-Worker_1-    mtime = os.stat(filename).st_mtime
2024-11-19 11:46:52,811-DEBUG-Worker_1-FileNotFoundError: [Errno 2] No such file or directory: '/home/leiroux/Videos/The Ultimate Roulette of Speedrunning--f5xLVvvbFU-1920x1080-20221007.mkv'
2024-11-19 11:46:52,811-DEBUG-Worker_1-Child process exited with non-zero code: 1
```

#### What operating system do you use ?

Ubuntu 24.04 (Noble Numbat)

#### List of actions to perform to reproduce the problem:

  1. .. Installed Ubuntu OS
  2. .. Installed ffmpeg and yt-dlg via app store / snap
  3. .. set download config options; and ran url.

#### What is the expected behaviour ?
Download video embed thumbnail, subtitles, metadata, etc. convert to mp4 as a single file.

#### What happens instead ?
fails with ffmpeg not being detected.

---

Used the following addional options
--sub-langs all 
--compat-options no-live-chat 
--embed-subs 
--recode-video mp4
--format bestvideo+bestaudio+mergeall 
--embed-thumbnail 
--merge-output-format mkv
--embed-metadata
--embed-chapters 
--yes-playlist

file format name set as custom "%(title)s-%(id)s-%(resolution)s-%(upload_date)s.%(ext)s"

tried changing file format name to default settings, same issue.

Tried adding and removing the additional option:
--ffmpeg-location /usr/bin/ffmpeg

ffmpeg is installed with "whereis ffmpeg" command showing "ffmpeg: /usr/bin/ffmpeg"

Confirmed ffmpeg is installed calling it using ""ffmpeg -version"
```
ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100

```

Confirmed yt-dlp works fine with same settings using the command 

```
yt-dlp --sub-langs all --compat-options no-live-chat --embed-subs --recode-video mp4 --format bestvideo+bestaudio+mergeall --embed-thumbnail --merge-output-format mkv --embed-metadata --embed-chapters --yes-playlist https://www.youtube.com/watch?v=-f5xLVvvbFU
```

Tried installing via snap and via apt install for both ffmpeg and yt-dlp. yt-dlg does not detect ffmpeg still. Also installed via app center "ffmpeg-2204" and "ffmpeg library content snap" along with regular "ffmpeg"

**Comment by sfilie03** [comment]
Hi. I don't know much about ubuntu ffmpeg not being detected, even though I'd like to be able to help you, but recently I noticed yt-dlg on Windows 10 doesn't seem to be converting downloaded youtube files to .mp3. It only downloads them as .webm, so I don't know if maybe that's an issue with ffmpeg not being installed or detected by yt-dlg as well, however, I have the same version of yt-dlg installed on another computer, and it works properly. Here's the issue I posted "https://github.com/yt-dlg/yt-dlg/issues/28". Could you help me with it? Anyways, hopefully someone can help you find a solution for your issue. Thanks, and have a good day.

**Comment by bonn2** [comment]
I'm running into the same issue, my best theory right now is that the snap does not bundle ffmpeg and because of their sandboxing cannot access the default ubuntu system install of ffmpeg. If I'm not mistaken this should be work-around able, by getting a snap installation of ffmpeg connected to the snap for yt-dlg. I haven't quite figured this out yet, but I will report back if I get it working. Or if maybe someone beats me to it.
