### ISSUE TITLE
Can't launch if last download location doesn't exist, v1.8.1

### ISSUE THREAD

**Issue by taotien** [yt-dlg/yt-dlg#3]
### Bug report
```
Traceback (most recent call last):
  File "youtube_dl_gui\__main__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "youtube_dl_gui\app.py", line 123, in <module>
  File "youtube_dl_gui\mainframe.py", line 503, in __init__
  File "youtube_dl_gui\mainframe.py", line 782, in _update_savepath
  File "os.py", line 223, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\'
```

#### What operating system do you use ?

Windows 10

#### List of actions to perform to reproduce the problem:

  1. Set download location to non-persistent location (external drive, network, temporary folder, etc.)
  2. Exit yt-dlg
  3. Start yt-dlg

#### What is the expected behaviour ?

yt-dlg launches, either gives error when trying to save to the set but missing location, or defaults to path that exists.

#### What happens instead ?

The traceback and failure to launch.

**Comment by oleksis** [comment]
Can you describe the steps to throw the error?

**Comment by taotien** [comment]
The error shows when trying to launch yt-dlg again. Say the download location was a USB stick mounted on D:\\, if I close yt-dlg and eject the drive, then later open yt-dlg, it only shows the traceback. If I plug the USB back in, yt-dlg launches cleanly. The current workaround is to always remember to set the download location to the user desktop before closing.

**Comment by oleksis** [comment]
You can check a temporary manual solution in [this comment](https://github.com/oleksis/youtube-dl-gui/issues/65#issuecomment-947863640)
