### ISSUE TITLE
Cannot install yt-dlg through pip

### ISSUE THREAD

**Issue by Dyrimon** [yt-dlg/yt-dlg#8]
- [x] **I think** my problem is **NOT** with **youtube-dl** or **yt-dlp**
  - [ ] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **yt-dlp**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
### Bug report
I'm trying to install yt-dlg from pypi, but it shows error. pip suggests the problem is with packaging. Error log below:

```
pip3 install yt-dlg
Defaulting to user installation because normal site-packages is not writeable
Collecting yt-dlg
  Using cached yt_dlg-1.8.4-py3-none-any.whl (124 kB)
Collecting wxPython<=4.2.1a1,>=4.0.7.post2
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-86cg32bx/wxpython_5fa21c90f23347229b5604350c8ef896/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-86cg32bx/wxpython_5fa21c90f23347229b5604350c8ef896/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

#### What operating system do you use ?
Fedora 36
KDE Plasma desktop

#### List of actions to perform to reproduce the problem:

  1. Run pip3 install yt-dlg
  2. Error shows

#### What is the expected behaviour ?
pip should install yt-dlg without any problems

#### What happens instead ?
yt-dlg fails to get installed.

---

**Comment by Kadah** [comment]
`pip3 install attrdict`

Then try again.

**Comment by oleksis** [comment]
This is related to the issue wxWidgets/Phoenix/issues/2225 with `wxPython` 4.2.0

**Comment by Dyrimon** [comment]
> `pip3 install attrdict`
> 
> Then try again.

Installed both `attrdict` and `attrdict3`. Now it's showing a whole lot of new trouble:
```
pip3 install yt-dlg
Defaulting to user installation because normal site-packages is not writeable
Collecting yt-dlg
  Using cached yt_dlg-1.8.5-py3-none-any.whl (231 kB)
Collecting pypubsub>=4.0.3
  Using cached Pypubsub-4.0.3-py3-none-any.whl (61 kB)
Collecting wxPython<=4.2.1a1,>=4.0.7.post2
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /usr/lib64/python3.11/site-packages (from wxPython<=4.2.1a1,>=4.0.7.post2->yt-dlg) (9.2.0)
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from wxPython<=4.2.1a1,>=4.0.7.post2->yt-dlg) (1.16.0)
Requirement already satisfied: numpy in /usr/lib64/python3.11/site-packages (from wxPython<=4.2.1a1,>=4.0.7.post2->yt-dlg) (1.22.0)
Using legacy 'setup.py install' for wxPython, since package 'wheel' is not installed.
Installing collected packages: wxPython, pypubsub, yt-dlg
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [142 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /usr/lib/python3.11/site-packages/setuptools/dist.py:318: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      /usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
      
      "/usr/bin/python3" -u build.py build
      Will build using: "/usr/bin/python3"
      3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.0
      
      Running command: build
      Running command: build_wx
      wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
      Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
      /tmp/pip-install-kmm8g1mx/wxpython_eb1d5d11ff6d4cf9a7f07911f04f31cc/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
      checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking for toolkit... gtk
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether we are using the Intel C compiler... no
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking whether gcc needs -traditional... no
      checking for g++... g++
      checking whether we are using the GNU C++ compiler... yes
      checking whether g++ accepts -g... yes
      checking whether we are using the Intel C++ compiler... no
      checking whether we are using the Sun C++ compiler... no
      checking for ar... ar
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for langinfo.h... yes
      checking for wchar.h... yes
      checking for sys/select.h... yes
      checking for cxxabi.h... yes
      checking for an ANSI C-conforming const... yes
      checking for inline... inline
      checking size of short... 2
      checking size of void *... 8
      checking size of int... 4
      checking size of long... 8
      checking size of size_t... 8
      checking size of long long... 8
      checking size of wchar_t... 4
      checking for va_copy... yes
      checking for _FILE_OFFSET_BITS value needed for large files... 64
      checking if large file support is available... yes
      checking for _LARGEFILE_SOURCE value needed for large files... no
      checking whether byte ordering is bigendian... no
      checking for std::wstring in <string>... yes
      checking for std::istream... yes
      checking for std::ostream... yes
      checking for type_traits... yes
      checking for __sync_xxx_and_fetch builtins... yes
      checking for libraries directories... /usr/lib64
      checking for cos... no
      checking for floor... no
      checking if floating point functions link without -lm... no
      checking for sin... yes
      checking for ceil... yes
      checking if floating point functions link with -lm... yes
      checking for strtoull... yes
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for LIBPCRE... yes
      checking for zlib.h >= 1.1.4... yes
      checking for zlib.h... (cached) yes
      checking for deflate in -lz... yes
      checking for png.h > 0.90... no
      checking for png.h... (cached) no
      configure: WARNING: system png library not found or too old, will use built-in instead
      checking whether png.c file exists... yes
      checking for jpeglib.h... no
      configure: WARNING: system jpeg library not found, will use built-in instead
      checking whether jpeglib.h file exists... yes
      checking for jbg_dec_init in -ljbig... no
      checking for LIBTIFF... not found via pkg-config
      checking for tiffio.h... no
      configure: WARNING: system tiff library not found, will use built-in instead
      checking whether tiff.h file exists... yes
      checking for expat.h... no
      configure: WARNING: system expat library not found, will use built-in instead
      checking whether expat.h file exists... yes
      checking for gcc option to accept ISO C99... none needed
      checking for LIBCURL... not found
      checking for GTK+ version...
      checking for pkg-config... (cached) /usr/bin/pkg-config
      checking pkg-config is at least version 0.16... yes
      checking for GTK+ - version >= 3.0.0... no
      *** Could not run GTK+ test program, checking why...
      *** The test program failed to compile or link. See the file config.log for the
      *** exact error that occurred. This usually means GTK+ is incorrectly installed.
      configure: error:
      The development files for GTK+ were not found. For GTK+ 2, please
      ensure that pkg-config is in the path and that gtk+-2.0.pc is
      installed. For GTK+ 1.2 please check that gtk-config is in the path,
      and that the version is 1.2.3 or above. Also check that the
      libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
      --libs' are in the LD_LIBRARY_PATH or equivalent.
      
      Error running configure
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "/tmp/pip-install-kmm8g1mx/wxpython_eb1d5d11ff6d4cf9a7f07911f04f31cc/build.py", line 1563, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "/tmp/pip-install-kmm8g1mx/wxpython_eb1d5d11ff6d4cf9a7f07911f04f31cc/buildtools/build_wxwidgets.py", line 379, in main
          exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
        File "/tmp/pip-install-kmm8g1mx/wxpython_eb1d5d11ff6d4cf9a7f07911f04f31cc/buildtools/build_wxwidgets.py", line 72, in exitIfError
          raise builder.BuildError(msg)
      buildtools.builder.BuildError: Error running configure
      Finished command: build_wx (1m1.479s)
      Finished command: build (1m1.479s)
      Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by oleksis** [comment]
@Dyrimon Read this [issue](https://github.com/yt-dlg/yt-dlg/issues/8#issuecomment-1364547454)
